// Code generated by Kitex v0.9.1. DO NOT EDIT.
package serverreflection

import (
	reflection_v1alpha "github.com/cloudwego/kitex/pkg/reflection/grpc/reflection_v1alpha"
	server "github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler reflection_v1alpha.ServerReflection, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler reflection_v1alpha.ServerReflection, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
