// Copyright 2022 CloudWeGo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package tpl

// InvokerTpl is the template for generating invoker.go.
var InvokerTpl string = `// Code generated by Kitex {{.Version}}. DO NOT EDIT.

package {{ToLower .ServiceName}}

import (
	{{- range $path, $aliases := .Imports}}
		{{- if not $aliases}}
			"{{$path}}"
		{{- else}}
			{{- range $alias, $is := $aliases}}
				{{$alias}} "{{$path}}"
			{{- end}}
		{{- end}}
	{{- end}}
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler {{call .ServiceTypeName}}, opts ...server.Option) server.Invoker {
	var options []server.Option
    {{template "@invoker.go-NewInvoker-option" .}}
	options = append(options, opts...)

    s := server.NewInvoker(options...)
    if err := s.RegisterService(serviceInfo(), handler); err != nil {
            panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	{{- if .FrugalPretouch}}
	pretouch()
	{{- end}}{{/* if .FrugalPretouch */}}
    return s
}
{{template "@invoker.go-EOF" .}}
`
