// Copyright 2024 CloudWeGo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package tpl

var ClientMockTpl = `
// Code generated by MockGen. DO NOT EDIT.
// Source: kitex_gen/example/shop/item/itemserviceb/client.go
//
// Generated by this command:
//
//	___1go_build_go_uber_org_mock_mockgen -source=kitex_gen/example/shop/item/itemserviceb/client.go -destination=client_mock.go -package=main
//

// Package main is a generated GoMock package.
`
