header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: CloudWeGo Authors

  paths:
    - "**/*.go"
    - "**/*.s"

  paths-ignore:
    - internal/mocks/thrift/test.go
    - pkg/remote/codec/thrift/thrift_frugal.go
    - pkg/remote/codec/thrift/thrift_frugal_test.go
    - pkg/remote/codec/thrift/thrift_others.go
    - pkg/remote/trans/nphttp2/codes/codes.go
    - pkg/remote/trans/nphttp2/grpc/grpcframe/
    - pkg/remote/trans/nphttp2/grpc/bdp_estimator.go
    - pkg/remote/trans/nphttp2/grpc/controlbuf.go
    - pkg/remote/trans/nphttp2/grpc/defaults.go
    - pkg/remote/trans/nphttp2/grpc/framer.go
    - pkg/remote/trans/nphttp2/grpc/flowcontrol.go
    - pkg/remote/trans/nphttp2/grpc/http2_client.go
    - pkg/remote/trans/nphttp2/grpc/http2_server.go
    - pkg/remote/trans/nphttp2/grpc/http_util.go
    - pkg/remote/trans/nphttp2/grpc/keepalive.go
    - pkg/remote/trans/nphttp2/grpc/transport.go
    - pkg/remote/trans/nphttp2/metadata/metadata.go
    - pkg/remote/trans/nphttp2/status/status.go
    - pkg/remote/codec/protobuf/error.pb.go
    - pkg/remote/codec/protobuf/test.pb.go
    - pkg/generic/descriptor/tree.go
    - pkg/generic/descriptor/tree_test.go
    - pkg/generic/httppb_test/idl/echo.pb.go
    - pkg/utils/json.go
    - pkg/protocol/bthrift/test/kitex_gen/**

  comment: on-failure
