/*
 * Copyright 2022 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: ads.proto

package v3

import (
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	v3discovery "github.com/envoyproxy/go-control-plane/envoy/service/discovery/v3"
)

// Code generated by Kitex v0.3.4. DO NOT EDIT.

type AggregatedDiscoveryService interface {
	StreamAggregatedResources(stream AggregatedDiscoveryService_StreamAggregatedResourcesServer) (err error)
	DeltaAggregatedResources(stream AggregatedDiscoveryService_DeltaAggregatedResourcesServer) (err error)
}

type AggregatedDiscoveryService_StreamAggregatedResourcesServer interface {
	streaming.Stream
	Recv() (*v3discovery.DiscoveryRequest, error)
	Send(*v3discovery.DiscoveryResponse) error
}

type AggregatedDiscoveryService_DeltaAggregatedResourcesServer interface {
	streaming.Stream
	Recv() (*v3discovery.DeltaDiscoveryRequest, error)
	Send(*v3discovery.DeltaDiscoveryResponse) error
}
