/*
 * Copyright 2021 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by mockery v2.9.4. DO NOT EDIT.

package limiter

import mock "github.com/stretchr/testify/mock"

// LimitReporter is an autogenerated mock type for the LimitReporter type
type LimitReporter struct {
	mock.Mock
}

// ConnOverloadReport provides a mock function with given fields:
func (_m *LimitReporter) ConnOverloadReport() {
	_m.Called()
}

// QPSOverloadReport provides a mock function with given fields:
func (_m *LimitReporter) QPSOverloadReport() {
	_m.Called()
}
