// Code generated by Kitex v0.9.1. DO NOT EDIT.

package serverreflection

import (
	reflection_v1 "github.com/cloudwego/kitex/pkg/reflection/grpc/reflection_v1"
	server "github.com/cloudwego/kitex/server"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler reflection_v1.ServerReflection, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
