// Code generated by Kitex v0.6.0. DO NOT EDIT.
package exampleservice

import (
	kitex_gen "github.com/cloudwego/kitex/pkg/generic/proto_test/kitex_gen/kitex_gen"
	server "github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler kitex_gen.ExampleService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
