// Code generated by thriftgo (0.3.13). DO NOT EDIT.

package test

import (
	"bytes"
	"database/sql"
	"database/sql/driver"
	"fmt"
	"github.com/cloudwego/thriftgo/generator/golang/extension/unknown"
	"strings"
)

type AEnum int64

const (
	AEnum_A AEnum = 1
	AEnum_B AEnum = 2
)

func (p AEnum) String() string {
	switch p {
	case AEnum_A:
		return "A"
	case AEnum_B:
		return "B"
	}
	return "<UNSET>"
}

func AEnumFromString(s string) (AEnum, error) {
	switch s {
	case "A":
		return AEnum_A, nil
	case "B":
		return AEnum_B, nil
	}
	return AEnum(0), fmt.Errorf("not a valid AEnum string")
}

func AEnumPtr(v AEnum) *AEnum { return &v }
func (p *AEnum) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = AEnum(result.Int64)
	return
}

func (p *AEnum) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type HTTPStatus int64

const (
	HTTPStatus_OK        HTTPStatus = 200
	HTTPStatus_NOT_FOUND HTTPStatus = 404
)

func (p HTTPStatus) String() string {
	switch p {
	case HTTPStatus_OK:
		return "OK"
	case HTTPStatus_NOT_FOUND:
		return "NOT_FOUND"
	}
	return "<UNSET>"
}

func HTTPStatusFromString(s string) (HTTPStatus, error) {
	switch s {
	case "OK":
		return HTTPStatus_OK, nil
	case "NOT_FOUND":
		return HTTPStatus_NOT_FOUND, nil
	}
	return HTTPStatus(0), fmt.Errorf("not a valid HTTPStatus string")
}

func HTTPStatusPtr(v HTTPStatus) *HTTPStatus { return &v }
func (p *HTTPStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = HTTPStatus(result.Int64)
	return
}

func (p *HTTPStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type Inner struct {
	Num            int32             `thrift:"Num,1,optional" frugal:"1,optional,i32" json:"Num,omitempty"`
	Desc           *string           `thrift:"desc,2,optional" frugal:"2,optional,string" json:"desc,omitempty"`
	MapOfList      map[int64][]int64 `thrift:"MapOfList,3,optional" frugal:"3,optional,map<i64:list<i64>>" json:"MapOfList,omitempty"`
	MapOfEnumKey   map[AEnum]int64   `thrift:"MapOfEnumKey,4,optional" frugal:"4,optional,map<AEnum:i64>" json:"MapOfEnumKey,omitempty"`
	Byte1          *int8             `thrift:"Byte1,5,optional" frugal:"5,optional,byte" json:"Byte1,omitempty"`
	Double1        *float64          `thrift:"Double1,6,optional" frugal:"6,optional,double" json:"Double1,omitempty"`
	_unknownFields unknown.Fields
}

func NewInner() *Inner {
	return &Inner{

		Num: 5,
	}
}

func (p *Inner) InitDefault() {
	p.Num = 5
}

var Inner_Num_DEFAULT int32 = 5

func (p *Inner) GetNum() (v int32) {
	if !p.IsSetNum() {
		return Inner_Num_DEFAULT
	}
	return p.Num
}

var Inner_Desc_DEFAULT string

func (p *Inner) GetDesc() (v string) {
	if !p.IsSetDesc() {
		return Inner_Desc_DEFAULT
	}
	return *p.Desc
}

var Inner_MapOfList_DEFAULT map[int64][]int64

func (p *Inner) GetMapOfList() (v map[int64][]int64) {
	if !p.IsSetMapOfList() {
		return Inner_MapOfList_DEFAULT
	}
	return p.MapOfList
}

var Inner_MapOfEnumKey_DEFAULT map[AEnum]int64

func (p *Inner) GetMapOfEnumKey() (v map[AEnum]int64) {
	if !p.IsSetMapOfEnumKey() {
		return Inner_MapOfEnumKey_DEFAULT
	}
	return p.MapOfEnumKey
}

var Inner_Byte1_DEFAULT int8

func (p *Inner) GetByte1() (v int8) {
	if !p.IsSetByte1() {
		return Inner_Byte1_DEFAULT
	}
	return *p.Byte1
}

var Inner_Double1_DEFAULT float64

func (p *Inner) GetDouble1() (v float64) {
	if !p.IsSetDouble1() {
		return Inner_Double1_DEFAULT
	}
	return *p.Double1
}
func (p *Inner) SetNum(val int32) {
	p.Num = val
}
func (p *Inner) SetDesc(val *string) {
	p.Desc = val
}
func (p *Inner) SetMapOfList(val map[int64][]int64) {
	p.MapOfList = val
}
func (p *Inner) SetMapOfEnumKey(val map[AEnum]int64) {
	p.MapOfEnumKey = val
}
func (p *Inner) SetByte1(val *int8) {
	p.Byte1 = val
}
func (p *Inner) SetDouble1(val *float64) {
	p.Double1 = val
}

func (p *Inner) CarryingUnknownFields() bool {
	return len(p._unknownFields) > 0
}

func (p *Inner) IsSetNum() bool {
	return p.Num != Inner_Num_DEFAULT
}

func (p *Inner) IsSetDesc() bool {
	return p.Desc != nil
}

func (p *Inner) IsSetMapOfList() bool {
	return p.MapOfList != nil
}

func (p *Inner) IsSetMapOfEnumKey() bool {
	return p.MapOfEnumKey != nil
}

func (p *Inner) IsSetByte1() bool {
	return p.Byte1 != nil
}

func (p *Inner) IsSetDouble1() bool {
	return p.Double1 != nil
}

func (p *Inner) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Inner(%+v)", *p)
}

func (p *Inner) DeepEqual(ano *Inner) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Num) {
		return false
	}
	if !p.Field2DeepEqual(ano.Desc) {
		return false
	}
	if !p.Field3DeepEqual(ano.MapOfList) {
		return false
	}
	if !p.Field4DeepEqual(ano.MapOfEnumKey) {
		return false
	}
	if !p.Field5DeepEqual(ano.Byte1) {
		return false
	}
	if !p.Field6DeepEqual(ano.Double1) {
		return false
	}
	return true
}

func (p *Inner) Field1DeepEqual(src int32) bool {

	if p.Num != src {
		return false
	}
	return true
}
func (p *Inner) Field2DeepEqual(src *string) bool {

	if p.Desc == src {
		return true
	} else if p.Desc == nil || src == nil {
		return false
	}
	if strings.Compare(*p.Desc, *src) != 0 {
		return false
	}
	return true
}
func (p *Inner) Field3DeepEqual(src map[int64][]int64) bool {

	if len(p.MapOfList) != len(src) {
		return false
	}
	for k, v := range p.MapOfList {
		_src := src[k]
		if len(v) != len(_src) {
			return false
		}
		for i, v := range v {
			_src1 := _src[i]
			if v != _src1 {
				return false
			}
		}
	}
	return true
}
func (p *Inner) Field4DeepEqual(src map[AEnum]int64) bool {

	if len(p.MapOfEnumKey) != len(src) {
		return false
	}
	for k, v := range p.MapOfEnumKey {
		_src := src[k]
		if v != _src {
			return false
		}
	}
	return true
}
func (p *Inner) Field5DeepEqual(src *int8) bool {

	if p.Byte1 == src {
		return true
	} else if p.Byte1 == nil || src == nil {
		return false
	}
	if *p.Byte1 != *src {
		return false
	}
	return true
}
func (p *Inner) Field6DeepEqual(src *float64) bool {

	if p.Double1 == src {
		return true
	} else if p.Double1 == nil || src == nil {
		return false
	}
	if *p.Double1 != *src {
		return false
	}
	return true
}

var fieldIDToName_Inner = map[int16]string{
	1: "Num",
	2: "desc",
	3: "MapOfList",
	4: "MapOfEnumKey",
	5: "Byte1",
	6: "Double1",
}

type Local struct {
	L              int32 `thrift:"l,1" frugal:"1,default,i32" json:"l"`
	_unknownFields unknown.Fields
}

func NewLocal() *Local {
	return &Local{}
}

func (p *Local) InitDefault() {
}

func (p *Local) GetL() (v int32) {
	return p.L
}
func (p *Local) SetL(val int32) {
	p.L = val
}

func (p *Local) CarryingUnknownFields() bool {
	return len(p._unknownFields) > 0
}

func (p *Local) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Local(%+v)", *p)
}

func (p *Local) DeepEqual(ano *Local) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.L) {
		return false
	}
	return true
}

func (p *Local) Field1DeepEqual(src int32) bool {

	if p.L != src {
		return false
	}
	return true
}

var fieldIDToName_Local = map[int16]string{
	1: "l",
}

type FullStruct struct {
	Left           int32                              `thrift:"Left,1,required" frugal:"1,required,i32" json:"Left"`
	Right          int32                              `thrift:"Right,2,optional" frugal:"2,optional,i32" json:"Right,omitempty"`
	Dummy          []byte                             `thrift:"Dummy,3" frugal:"3,default,binary" json:"Dummy"`
	InnerReq       *Inner                             `thrift:"InnerReq,4" frugal:"4,default,Inner" json:"InnerReq"`
	Status         HTTPStatus                         `thrift:"status,5" frugal:"5,default,HTTPStatus" json:"status"`
	Str            string                             `thrift:"Str,6" frugal:"6,default,string" json:"Str"`
	EnumList       []HTTPStatus                       `thrift:"enum_list,7" frugal:"7,default,list<HTTPStatus>" json:"enum_list"`
	Strmap         map[int32]string                   `thrift:"Strmap,8,optional" frugal:"8,optional,map<i32:string>" json:"Strmap,omitempty"`
	Int64          int64                              `thrift:"Int64,9" frugal:"9,default,i64" json:"Int64"`
	IntList        []int32                            `thrift:"IntList,10,optional" frugal:"10,optional,list<i32>" json:"IntList,omitempty"`
	LocalList      []*Local                           `thrift:"localList,11" frugal:"11,default,list<Local>" json:"localList"`
	StrLocalMap    map[string]*Local                  `thrift:"StrLocalMap,12" frugal:"12,default,map<string:Local>" json:"StrLocalMap"`
	NestList       [][]int32                          `thrift:"nestList,13" frugal:"13,default,list<list<i32>>" json:"nestList"`
	RequiredIns    *Local                             `thrift:"required_ins,14,required" frugal:"14,required,Local" json:"required_ins"`
	NestMap        map[string][]string                `thrift:"nestMap,16" frugal:"16,default,map<string:list<string>>" json:"nestMap"`
	NestMap2       []map[string]HTTPStatus            `thrift:"nestMap2,17" frugal:"17,default,list<map<string:HTTPStatus>>" json:"nestMap2"`
	EnumMap        map[int32]HTTPStatus               `thrift:"enum_map,18" frugal:"18,default,map<i32:HTTPStatus>" json:"enum_map"`
	Strlist        []string                           `thrift:"Strlist,19" frugal:"19,default,list<string>" json:"Strlist"`
	OptionalIns    *Local                             `thrift:"optional_ins,20,optional" frugal:"20,optional,Local" json:"optional_ins,omitempty"`
	AnotherInner   *Inner                             `thrift:"AnotherInner,21" frugal:"21,default,Inner" json:"AnotherInner"`
	OptNilList     []string                           `thrift:"opt_nil_list,22,optional" frugal:"22,optional,list<string>" json:"opt_nil_list,omitempty"`
	NilList        []string                           `thrift:"nil_list,23" frugal:"23,default,list<string>" json:"nil_list"`
	OptNilInsList  []*Inner                           `thrift:"opt_nil_ins_list,24,optional" frugal:"24,optional,list<Inner>" json:"opt_nil_ins_list,omitempty"`
	NilInsList     []*Inner                           `thrift:"nil_ins_list,25" frugal:"25,default,list<Inner>" json:"nil_ins_list"`
	OptStatus      *HTTPStatus                        `thrift:"opt_status,26,optional" frugal:"26,optional,HTTPStatus" json:"opt_status,omitempty"`
	EnumKeyMap     map[HTTPStatus]*Local              `thrift:"enum_key_map,27" frugal:"27,default,map<HTTPStatus:Local>" json:"enum_key_map"`
	Complex        map[HTTPStatus][]map[string]*Local `thrift:"complex,28" frugal:"28,default,map<HTTPStatus:list<map<string:Local>>>" json:"complex"`
	I64Set         []int64                            `thrift:"i64Set,29" frugal:"29,default,set<i64>" json:"i64Set"`
	Int16          int16                              `thrift:"Int16,30" frugal:"30,default,i16" json:"Int16"`
	IsSet          bool                               `thrift:"isSet,31" frugal:"31,default,bool" json:"isSet"`
	_unknownFields unknown.Fields
}

func NewFullStruct() *FullStruct {
	return &FullStruct{

		Right: 3,
	}
}

func (p *FullStruct) InitDefault() {
	p.Right = 3
}

func (p *FullStruct) GetLeft() (v int32) {
	return p.Left
}

var FullStruct_Right_DEFAULT int32 = 3

func (p *FullStruct) GetRight() (v int32) {
	if !p.IsSetRight() {
		return FullStruct_Right_DEFAULT
	}
	return p.Right
}

func (p *FullStruct) GetDummy() (v []byte) {
	return p.Dummy
}

var FullStruct_InnerReq_DEFAULT *Inner

func (p *FullStruct) GetInnerReq() (v *Inner) {
	if !p.IsSetInnerReq() {
		return FullStruct_InnerReq_DEFAULT
	}
	return p.InnerReq
}

func (p *FullStruct) GetStatus() (v HTTPStatus) {
	return p.Status
}

func (p *FullStruct) GetStr() (v string) {
	return p.Str
}

func (p *FullStruct) GetEnumList() (v []HTTPStatus) {
	return p.EnumList
}

var FullStruct_Strmap_DEFAULT map[int32]string

func (p *FullStruct) GetStrmap() (v map[int32]string) {
	if !p.IsSetStrmap() {
		return FullStruct_Strmap_DEFAULT
	}
	return p.Strmap
}

func (p *FullStruct) GetInt64() (v int64) {
	return p.Int64
}

var FullStruct_IntList_DEFAULT []int32

func (p *FullStruct) GetIntList() (v []int32) {
	if !p.IsSetIntList() {
		return FullStruct_IntList_DEFAULT
	}
	return p.IntList
}

func (p *FullStruct) GetLocalList() (v []*Local) {
	return p.LocalList
}

func (p *FullStruct) GetStrLocalMap() (v map[string]*Local) {
	return p.StrLocalMap
}

func (p *FullStruct) GetNestList() (v [][]int32) {
	return p.NestList
}

var FullStruct_RequiredIns_DEFAULT *Local

func (p *FullStruct) GetRequiredIns() (v *Local) {
	if !p.IsSetRequiredIns() {
		return FullStruct_RequiredIns_DEFAULT
	}
	return p.RequiredIns
}

func (p *FullStruct) GetNestMap() (v map[string][]string) {
	return p.NestMap
}

func (p *FullStruct) GetNestMap2() (v []map[string]HTTPStatus) {
	return p.NestMap2
}

func (p *FullStruct) GetEnumMap() (v map[int32]HTTPStatus) {
	return p.EnumMap
}

func (p *FullStruct) GetStrlist() (v []string) {
	return p.Strlist
}

var FullStruct_OptionalIns_DEFAULT *Local

func (p *FullStruct) GetOptionalIns() (v *Local) {
	if !p.IsSetOptionalIns() {
		return FullStruct_OptionalIns_DEFAULT
	}
	return p.OptionalIns
}

var FullStruct_AnotherInner_DEFAULT *Inner

func (p *FullStruct) GetAnotherInner() (v *Inner) {
	if !p.IsSetAnotherInner() {
		return FullStruct_AnotherInner_DEFAULT
	}
	return p.AnotherInner
}

var FullStruct_OptNilList_DEFAULT []string

func (p *FullStruct) GetOptNilList() (v []string) {
	if !p.IsSetOptNilList() {
		return FullStruct_OptNilList_DEFAULT
	}
	return p.OptNilList
}

func (p *FullStruct) GetNilList() (v []string) {
	return p.NilList
}

var FullStruct_OptNilInsList_DEFAULT []*Inner

func (p *FullStruct) GetOptNilInsList() (v []*Inner) {
	if !p.IsSetOptNilInsList() {
		return FullStruct_OptNilInsList_DEFAULT
	}
	return p.OptNilInsList
}

func (p *FullStruct) GetNilInsList() (v []*Inner) {
	return p.NilInsList
}

var FullStruct_OptStatus_DEFAULT HTTPStatus

func (p *FullStruct) GetOptStatus() (v HTTPStatus) {
	if !p.IsSetOptStatus() {
		return FullStruct_OptStatus_DEFAULT
	}
	return *p.OptStatus
}

func (p *FullStruct) GetEnumKeyMap() (v map[HTTPStatus]*Local) {
	return p.EnumKeyMap
}

func (p *FullStruct) GetComplex() (v map[HTTPStatus][]map[string]*Local) {
	return p.Complex
}

func (p *FullStruct) GetI64Set() (v []int64) {
	return p.I64Set
}

func (p *FullStruct) GetInt16() (v int16) {
	return p.Int16
}

func (p *FullStruct) GetIsSet() (v bool) {
	return p.IsSet
}
func (p *FullStruct) SetLeft(val int32) {
	p.Left = val
}
func (p *FullStruct) SetRight(val int32) {
	p.Right = val
}
func (p *FullStruct) SetDummy(val []byte) {
	p.Dummy = val
}
func (p *FullStruct) SetInnerReq(val *Inner) {
	p.InnerReq = val
}
func (p *FullStruct) SetStatus(val HTTPStatus) {
	p.Status = val
}
func (p *FullStruct) SetStr(val string) {
	p.Str = val
}
func (p *FullStruct) SetEnumList(val []HTTPStatus) {
	p.EnumList = val
}
func (p *FullStruct) SetStrmap(val map[int32]string) {
	p.Strmap = val
}
func (p *FullStruct) SetInt64(val int64) {
	p.Int64 = val
}
func (p *FullStruct) SetIntList(val []int32) {
	p.IntList = val
}
func (p *FullStruct) SetLocalList(val []*Local) {
	p.LocalList = val
}
func (p *FullStruct) SetStrLocalMap(val map[string]*Local) {
	p.StrLocalMap = val
}
func (p *FullStruct) SetNestList(val [][]int32) {
	p.NestList = val
}
func (p *FullStruct) SetRequiredIns(val *Local) {
	p.RequiredIns = val
}
func (p *FullStruct) SetNestMap(val map[string][]string) {
	p.NestMap = val
}
func (p *FullStruct) SetNestMap2(val []map[string]HTTPStatus) {
	p.NestMap2 = val
}
func (p *FullStruct) SetEnumMap(val map[int32]HTTPStatus) {
	p.EnumMap = val
}
func (p *FullStruct) SetStrlist(val []string) {
	p.Strlist = val
}
func (p *FullStruct) SetOptionalIns(val *Local) {
	p.OptionalIns = val
}
func (p *FullStruct) SetAnotherInner(val *Inner) {
	p.AnotherInner = val
}
func (p *FullStruct) SetOptNilList(val []string) {
	p.OptNilList = val
}
func (p *FullStruct) SetNilList(val []string) {
	p.NilList = val
}
func (p *FullStruct) SetOptNilInsList(val []*Inner) {
	p.OptNilInsList = val
}
func (p *FullStruct) SetNilInsList(val []*Inner) {
	p.NilInsList = val
}
func (p *FullStruct) SetOptStatus(val *HTTPStatus) {
	p.OptStatus = val
}
func (p *FullStruct) SetEnumKeyMap(val map[HTTPStatus]*Local) {
	p.EnumKeyMap = val
}
func (p *FullStruct) SetComplex(val map[HTTPStatus][]map[string]*Local) {
	p.Complex = val
}
func (p *FullStruct) SetI64Set(val []int64) {
	p.I64Set = val
}
func (p *FullStruct) SetInt16(val int16) {
	p.Int16 = val
}
func (p *FullStruct) SetIsSet(val bool) {
	p.IsSet = val
}

func (p *FullStruct) CarryingUnknownFields() bool {
	return len(p._unknownFields) > 0
}

func (p *FullStruct) IsSetRight() bool {
	return p.Right != FullStruct_Right_DEFAULT
}

func (p *FullStruct) IsSetInnerReq() bool {
	return p.InnerReq != nil
}

func (p *FullStruct) IsSetStrmap() bool {
	return p.Strmap != nil
}

func (p *FullStruct) IsSetIntList() bool {
	return p.IntList != nil
}

func (p *FullStruct) IsSetRequiredIns() bool {
	return p.RequiredIns != nil
}

func (p *FullStruct) IsSetOptionalIns() bool {
	return p.OptionalIns != nil
}

func (p *FullStruct) IsSetAnotherInner() bool {
	return p.AnotherInner != nil
}

func (p *FullStruct) IsSetOptNilList() bool {
	return p.OptNilList != nil
}

func (p *FullStruct) IsSetOptNilInsList() bool {
	return p.OptNilInsList != nil
}

func (p *FullStruct) IsSetOptStatus() bool {
	return p.OptStatus != nil
}

func (p *FullStruct) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FullStruct(%+v)", *p)
}

func (p *FullStruct) DeepEqual(ano *FullStruct) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Left) {
		return false
	}
	if !p.Field2DeepEqual(ano.Right) {
		return false
	}
	if !p.Field3DeepEqual(ano.Dummy) {
		return false
	}
	if !p.Field4DeepEqual(ano.InnerReq) {
		return false
	}
	if !p.Field5DeepEqual(ano.Status) {
		return false
	}
	if !p.Field6DeepEqual(ano.Str) {
		return false
	}
	if !p.Field7DeepEqual(ano.EnumList) {
		return false
	}
	if !p.Field8DeepEqual(ano.Strmap) {
		return false
	}
	if !p.Field9DeepEqual(ano.Int64) {
		return false
	}
	if !p.Field10DeepEqual(ano.IntList) {
		return false
	}
	if !p.Field11DeepEqual(ano.LocalList) {
		return false
	}
	if !p.Field12DeepEqual(ano.StrLocalMap) {
		return false
	}
	if !p.Field13DeepEqual(ano.NestList) {
		return false
	}
	if !p.Field14DeepEqual(ano.RequiredIns) {
		return false
	}
	if !p.Field16DeepEqual(ano.NestMap) {
		return false
	}
	if !p.Field17DeepEqual(ano.NestMap2) {
		return false
	}
	if !p.Field18DeepEqual(ano.EnumMap) {
		return false
	}
	if !p.Field19DeepEqual(ano.Strlist) {
		return false
	}
	if !p.Field20DeepEqual(ano.OptionalIns) {
		return false
	}
	if !p.Field21DeepEqual(ano.AnotherInner) {
		return false
	}
	if !p.Field22DeepEqual(ano.OptNilList) {
		return false
	}
	if !p.Field23DeepEqual(ano.NilList) {
		return false
	}
	if !p.Field24DeepEqual(ano.OptNilInsList) {
		return false
	}
	if !p.Field25DeepEqual(ano.NilInsList) {
		return false
	}
	if !p.Field26DeepEqual(ano.OptStatus) {
		return false
	}
	if !p.Field27DeepEqual(ano.EnumKeyMap) {
		return false
	}
	if !p.Field28DeepEqual(ano.Complex) {
		return false
	}
	if !p.Field29DeepEqual(ano.I64Set) {
		return false
	}
	if !p.Field30DeepEqual(ano.Int16) {
		return false
	}
	if !p.Field31DeepEqual(ano.IsSet) {
		return false
	}
	return true
}

func (p *FullStruct) Field1DeepEqual(src int32) bool {

	if p.Left != src {
		return false
	}
	return true
}
func (p *FullStruct) Field2DeepEqual(src int32) bool {

	if p.Right != src {
		return false
	}
	return true
}
func (p *FullStruct) Field3DeepEqual(src []byte) bool {

	if bytes.Compare(p.Dummy, src) != 0 {
		return false
	}
	return true
}
func (p *FullStruct) Field4DeepEqual(src *Inner) bool {

	if !p.InnerReq.DeepEqual(src) {
		return false
	}
	return true
}
func (p *FullStruct) Field5DeepEqual(src HTTPStatus) bool {

	if p.Status != src {
		return false
	}
	return true
}
func (p *FullStruct) Field6DeepEqual(src string) bool {

	if strings.Compare(p.Str, src) != 0 {
		return false
	}
	return true
}
func (p *FullStruct) Field7DeepEqual(src []HTTPStatus) bool {

	if len(p.EnumList) != len(src) {
		return false
	}
	for i, v := range p.EnumList {
		_src := src[i]
		if v != _src {
			return false
		}
	}
	return true
}
func (p *FullStruct) Field8DeepEqual(src map[int32]string) bool {

	if len(p.Strmap) != len(src) {
		return false
	}
	for k, v := range p.Strmap {
		_src := src[k]
		if strings.Compare(v, _src) != 0 {
			return false
		}
	}
	return true
}
func (p *FullStruct) Field9DeepEqual(src int64) bool {

	if p.Int64 != src {
		return false
	}
	return true
}
func (p *FullStruct) Field10DeepEqual(src []int32) bool {

	if len(p.IntList) != len(src) {
		return false
	}
	for i, v := range p.IntList {
		_src := src[i]
		if v != _src {
			return false
		}
	}
	return true
}
func (p *FullStruct) Field11DeepEqual(src []*Local) bool {

	if len(p.LocalList) != len(src) {
		return false
	}
	for i, v := range p.LocalList {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}
func (p *FullStruct) Field12DeepEqual(src map[string]*Local) bool {

	if len(p.StrLocalMap) != len(src) {
		return false
	}
	for k, v := range p.StrLocalMap {
		_src := src[k]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}
func (p *FullStruct) Field13DeepEqual(src [][]int32) bool {

	if len(p.NestList) != len(src) {
		return false
	}
	for i, v := range p.NestList {
		_src := src[i]
		if len(v) != len(_src) {
			return false
		}
		for i, v := range v {
			_src1 := _src[i]
			if v != _src1 {
				return false
			}
		}
	}
	return true
}
func (p *FullStruct) Field14DeepEqual(src *Local) bool {

	if !p.RequiredIns.DeepEqual(src) {
		return false
	}
	return true
}
func (p *FullStruct) Field16DeepEqual(src map[string][]string) bool {

	if len(p.NestMap) != len(src) {
		return false
	}
	for k, v := range p.NestMap {
		_src := src[k]
		if len(v) != len(_src) {
			return false
		}
		for i, v := range v {
			_src1 := _src[i]
			if strings.Compare(v, _src1) != 0 {
				return false
			}
		}
	}
	return true
}
func (p *FullStruct) Field17DeepEqual(src []map[string]HTTPStatus) bool {

	if len(p.NestMap2) != len(src) {
		return false
	}
	for i, v := range p.NestMap2 {
		_src := src[i]
		if len(v) != len(_src) {
			return false
		}
		for k, v := range v {
			_src1 := _src[k]
			if v != _src1 {
				return false
			}
		}
	}
	return true
}
func (p *FullStruct) Field18DeepEqual(src map[int32]HTTPStatus) bool {

	if len(p.EnumMap) != len(src) {
		return false
	}
	for k, v := range p.EnumMap {
		_src := src[k]
		if v != _src {
			return false
		}
	}
	return true
}
func (p *FullStruct) Field19DeepEqual(src []string) bool {

	if len(p.Strlist) != len(src) {
		return false
	}
	for i, v := range p.Strlist {
		_src := src[i]
		if strings.Compare(v, _src) != 0 {
			return false
		}
	}
	return true
}
func (p *FullStruct) Field20DeepEqual(src *Local) bool {

	if !p.OptionalIns.DeepEqual(src) {
		return false
	}
	return true
}
func (p *FullStruct) Field21DeepEqual(src *Inner) bool {

	if !p.AnotherInner.DeepEqual(src) {
		return false
	}
	return true
}
func (p *FullStruct) Field22DeepEqual(src []string) bool {

	if len(p.OptNilList) != len(src) {
		return false
	}
	for i, v := range p.OptNilList {
		_src := src[i]
		if strings.Compare(v, _src) != 0 {
			return false
		}
	}
	return true
}
func (p *FullStruct) Field23DeepEqual(src []string) bool {

	if len(p.NilList) != len(src) {
		return false
	}
	for i, v := range p.NilList {
		_src := src[i]
		if strings.Compare(v, _src) != 0 {
			return false
		}
	}
	return true
}
func (p *FullStruct) Field24DeepEqual(src []*Inner) bool {

	if len(p.OptNilInsList) != len(src) {
		return false
	}
	for i, v := range p.OptNilInsList {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}
func (p *FullStruct) Field25DeepEqual(src []*Inner) bool {

	if len(p.NilInsList) != len(src) {
		return false
	}
	for i, v := range p.NilInsList {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}
func (p *FullStruct) Field26DeepEqual(src *HTTPStatus) bool {

	if p.OptStatus == src {
		return true
	} else if p.OptStatus == nil || src == nil {
		return false
	}
	if *p.OptStatus != *src {
		return false
	}
	return true
}
func (p *FullStruct) Field27DeepEqual(src map[HTTPStatus]*Local) bool {

	if len(p.EnumKeyMap) != len(src) {
		return false
	}
	for k, v := range p.EnumKeyMap {
		_src := src[k]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}
func (p *FullStruct) Field28DeepEqual(src map[HTTPStatus][]map[string]*Local) bool {

	if len(p.Complex) != len(src) {
		return false
	}
	for k, v := range p.Complex {
		_src := src[k]
		if len(v) != len(_src) {
			return false
		}
		for i, v := range v {
			_src1 := _src[i]
			if len(v) != len(_src1) {
				return false
			}
			for k, v := range v {
				_src2 := _src1[k]
				if !v.DeepEqual(_src2) {
					return false
				}
			}
		}
	}
	return true
}
func (p *FullStruct) Field29DeepEqual(src []int64) bool {

	if len(p.I64Set) != len(src) {
		return false
	}
	for i, v := range p.I64Set {
		_src := src[i]
		if v != _src {
			return false
		}
	}
	return true
}
func (p *FullStruct) Field30DeepEqual(src int16) bool {

	if p.Int16 != src {
		return false
	}
	return true
}
func (p *FullStruct) Field31DeepEqual(src bool) bool {

	if p.IsSet != src {
		return false
	}
	return true
}

var fieldIDToName_FullStruct = map[int16]string{
	1:  "Left",
	2:  "Right",
	3:  "Dummy",
	4:  "InnerReq",
	5:  "status",
	6:  "Str",
	7:  "enum_list",
	8:  "Strmap",
	9:  "Int64",
	10: "IntList",
	11: "localList",
	12: "StrLocalMap",
	13: "nestList",
	14: "required_ins",
	16: "nestMap",
	17: "nestMap2",
	18: "enum_map",
	19: "Strlist",
	20: "optional_ins",
	21: "AnotherInner",
	22: "opt_nil_list",
	23: "nil_list",
	24: "opt_nil_ins_list",
	25: "nil_ins_list",
	26: "opt_status",
	27: "enum_key_map",
	28: "complex",
	29: "i64Set",
	30: "Int16",
	31: "isSet",
}

type MixedStruct struct {
	Left           int32                 `thrift:"Left,1,required" frugal:"1,required,i32" json:"Left"`
	Dummy          []byte                `thrift:"Dummy,3" frugal:"3,default,binary" json:"Dummy"`
	Str            string                `thrift:"Str,6" frugal:"6,default,string" json:"Str"`
	EnumList       []HTTPStatus          `thrift:"enum_list,7" frugal:"7,default,list<HTTPStatus>" json:"enum_list"`
	Int64          int64                 `thrift:"Int64,9" frugal:"9,default,i64" json:"Int64"`
	IntList        []int32               `thrift:"IntList,10,optional" frugal:"10,optional,list<i32>" json:"IntList,omitempty"`
	LocalList      []*Local              `thrift:"localList,11" frugal:"11,default,list<Local>" json:"localList"`
	StrLocalMap    map[string]*Local     `thrift:"StrLocalMap,12" frugal:"12,default,map<string:Local>" json:"StrLocalMap"`
	NestList       [][]int32             `thrift:"nestList,13" frugal:"13,default,list<list<i32>>" json:"nestList"`
	RequiredIns    *Local                `thrift:"required_ins,14,required" frugal:"14,required,Local" json:"required_ins"`
	OptionalIns    *Local                `thrift:"optional_ins,20,optional" frugal:"20,optional,Local" json:"optional_ins,omitempty"`
	AnotherInner   *Inner                `thrift:"AnotherInner,21" frugal:"21,default,Inner" json:"AnotherInner"`
	EnumKeyMap     map[HTTPStatus]*Local `thrift:"enum_key_map,27" frugal:"27,default,map<HTTPStatus:Local>" json:"enum_key_map"`
	_unknownFields unknown.Fields
}

func NewMixedStruct() *MixedStruct {
	return &MixedStruct{}
}

func (p *MixedStruct) InitDefault() {
}

func (p *MixedStruct) GetLeft() (v int32) {
	return p.Left
}

func (p *MixedStruct) GetDummy() (v []byte) {
	return p.Dummy
}

func (p *MixedStruct) GetStr() (v string) {
	return p.Str
}

func (p *MixedStruct) GetEnumList() (v []HTTPStatus) {
	return p.EnumList
}

func (p *MixedStruct) GetInt64() (v int64) {
	return p.Int64
}

var MixedStruct_IntList_DEFAULT []int32

func (p *MixedStruct) GetIntList() (v []int32) {
	if !p.IsSetIntList() {
		return MixedStruct_IntList_DEFAULT
	}
	return p.IntList
}

func (p *MixedStruct) GetLocalList() (v []*Local) {
	return p.LocalList
}

func (p *MixedStruct) GetStrLocalMap() (v map[string]*Local) {
	return p.StrLocalMap
}

func (p *MixedStruct) GetNestList() (v [][]int32) {
	return p.NestList
}

var MixedStruct_RequiredIns_DEFAULT *Local

func (p *MixedStruct) GetRequiredIns() (v *Local) {
	if !p.IsSetRequiredIns() {
		return MixedStruct_RequiredIns_DEFAULT
	}
	return p.RequiredIns
}

var MixedStruct_OptionalIns_DEFAULT *Local

func (p *MixedStruct) GetOptionalIns() (v *Local) {
	if !p.IsSetOptionalIns() {
		return MixedStruct_OptionalIns_DEFAULT
	}
	return p.OptionalIns
}

var MixedStruct_AnotherInner_DEFAULT *Inner

func (p *MixedStruct) GetAnotherInner() (v *Inner) {
	if !p.IsSetAnotherInner() {
		return MixedStruct_AnotherInner_DEFAULT
	}
	return p.AnotherInner
}

func (p *MixedStruct) GetEnumKeyMap() (v map[HTTPStatus]*Local) {
	return p.EnumKeyMap
}
func (p *MixedStruct) SetLeft(val int32) {
	p.Left = val
}
func (p *MixedStruct) SetDummy(val []byte) {
	p.Dummy = val
}
func (p *MixedStruct) SetStr(val string) {
	p.Str = val
}
func (p *MixedStruct) SetEnumList(val []HTTPStatus) {
	p.EnumList = val
}
func (p *MixedStruct) SetInt64(val int64) {
	p.Int64 = val
}
func (p *MixedStruct) SetIntList(val []int32) {
	p.IntList = val
}
func (p *MixedStruct) SetLocalList(val []*Local) {
	p.LocalList = val
}
func (p *MixedStruct) SetStrLocalMap(val map[string]*Local) {
	p.StrLocalMap = val
}
func (p *MixedStruct) SetNestList(val [][]int32) {
	p.NestList = val
}
func (p *MixedStruct) SetRequiredIns(val *Local) {
	p.RequiredIns = val
}
func (p *MixedStruct) SetOptionalIns(val *Local) {
	p.OptionalIns = val
}
func (p *MixedStruct) SetAnotherInner(val *Inner) {
	p.AnotherInner = val
}
func (p *MixedStruct) SetEnumKeyMap(val map[HTTPStatus]*Local) {
	p.EnumKeyMap = val
}

func (p *MixedStruct) CarryingUnknownFields() bool {
	return len(p._unknownFields) > 0
}

func (p *MixedStruct) IsSetIntList() bool {
	return p.IntList != nil
}

func (p *MixedStruct) IsSetRequiredIns() bool {
	return p.RequiredIns != nil
}

func (p *MixedStruct) IsSetOptionalIns() bool {
	return p.OptionalIns != nil
}

func (p *MixedStruct) IsSetAnotherInner() bool {
	return p.AnotherInner != nil
}

func (p *MixedStruct) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MixedStruct(%+v)", *p)
}

func (p *MixedStruct) DeepEqual(ano *MixedStruct) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Left) {
		return false
	}
	if !p.Field3DeepEqual(ano.Dummy) {
		return false
	}
	if !p.Field6DeepEqual(ano.Str) {
		return false
	}
	if !p.Field7DeepEqual(ano.EnumList) {
		return false
	}
	if !p.Field9DeepEqual(ano.Int64) {
		return false
	}
	if !p.Field10DeepEqual(ano.IntList) {
		return false
	}
	if !p.Field11DeepEqual(ano.LocalList) {
		return false
	}
	if !p.Field12DeepEqual(ano.StrLocalMap) {
		return false
	}
	if !p.Field13DeepEqual(ano.NestList) {
		return false
	}
	if !p.Field14DeepEqual(ano.RequiredIns) {
		return false
	}
	if !p.Field20DeepEqual(ano.OptionalIns) {
		return false
	}
	if !p.Field21DeepEqual(ano.AnotherInner) {
		return false
	}
	if !p.Field27DeepEqual(ano.EnumKeyMap) {
		return false
	}
	return true
}

func (p *MixedStruct) Field1DeepEqual(src int32) bool {

	if p.Left != src {
		return false
	}
	return true
}
func (p *MixedStruct) Field3DeepEqual(src []byte) bool {

	if bytes.Compare(p.Dummy, src) != 0 {
		return false
	}
	return true
}
func (p *MixedStruct) Field6DeepEqual(src string) bool {

	if strings.Compare(p.Str, src) != 0 {
		return false
	}
	return true
}
func (p *MixedStruct) Field7DeepEqual(src []HTTPStatus) bool {

	if len(p.EnumList) != len(src) {
		return false
	}
	for i, v := range p.EnumList {
		_src := src[i]
		if v != _src {
			return false
		}
	}
	return true
}
func (p *MixedStruct) Field9DeepEqual(src int64) bool {

	if p.Int64 != src {
		return false
	}
	return true
}
func (p *MixedStruct) Field10DeepEqual(src []int32) bool {

	if len(p.IntList) != len(src) {
		return false
	}
	for i, v := range p.IntList {
		_src := src[i]
		if v != _src {
			return false
		}
	}
	return true
}
func (p *MixedStruct) Field11DeepEqual(src []*Local) bool {

	if len(p.LocalList) != len(src) {
		return false
	}
	for i, v := range p.LocalList {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}
func (p *MixedStruct) Field12DeepEqual(src map[string]*Local) bool {

	if len(p.StrLocalMap) != len(src) {
		return false
	}
	for k, v := range p.StrLocalMap {
		_src := src[k]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}
func (p *MixedStruct) Field13DeepEqual(src [][]int32) bool {

	if len(p.NestList) != len(src) {
		return false
	}
	for i, v := range p.NestList {
		_src := src[i]
		if len(v) != len(_src) {
			return false
		}
		for i, v := range v {
			_src1 := _src[i]
			if v != _src1 {
				return false
			}
		}
	}
	return true
}
func (p *MixedStruct) Field14DeepEqual(src *Local) bool {

	if !p.RequiredIns.DeepEqual(src) {
		return false
	}
	return true
}
func (p *MixedStruct) Field20DeepEqual(src *Local) bool {

	if !p.OptionalIns.DeepEqual(src) {
		return false
	}
	return true
}
func (p *MixedStruct) Field21DeepEqual(src *Inner) bool {

	if !p.AnotherInner.DeepEqual(src) {
		return false
	}
	return true
}
func (p *MixedStruct) Field27DeepEqual(src map[HTTPStatus]*Local) bool {

	if len(p.EnumKeyMap) != len(src) {
		return false
	}
	for k, v := range p.EnumKeyMap {
		_src := src[k]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}

var fieldIDToName_MixedStruct = map[int16]string{
	1:  "Left",
	3:  "Dummy",
	6:  "Str",
	7:  "enum_list",
	9:  "Int64",
	10: "IntList",
	11: "localList",
	12: "StrLocalMap",
	13: "nestList",
	14: "required_ins",
	20: "optional_ins",
	21: "AnotherInner",
	27: "enum_key_map",
}

type EmptyStruct struct {
	_unknownFields unknown.Fields
}

func NewEmptyStruct() *EmptyStruct {
	return &EmptyStruct{}
}

func (p *EmptyStruct) InitDefault() {
}

func (p *EmptyStruct) CarryingUnknownFields() bool {
	return len(p._unknownFields) > 0
}

func (p *EmptyStruct) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EmptyStruct(%+v)", *p)
}

func (p *EmptyStruct) DeepEqual(ano *EmptyStruct) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	return true
}

var fieldIDToName_EmptyStruct = map[int16]string{}
