/*
 * Copyright 2024 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by thriftgo (0.3.14). DO NOT EDIT.

package thrift

import (
	"context"
	"fmt"
	"strings"
)

type MockReq struct {
	Msg     string            `thrift:"Msg,1" frugal:"1,default,string" json:"Msg"`
	StrMap  map[string]string `thrift:"strMap,2" frugal:"2,default,map<string:string>" json:"strMap"`
	StrList []string          `thrift:"strList,3" frugal:"3,default,list<string>" json:"strList"`
}

func NewMockReq() *MockReq {
	return &MockReq{}
}

func (p *MockReq) InitDefault() {
}

func (p *MockReq) GetMsg() (v string) {
	return p.Msg
}

func (p *MockReq) GetStrMap() (v map[string]string) {
	return p.StrMap
}

func (p *MockReq) GetStrList() (v []string) {
	return p.StrList
}
func (p *MockReq) SetMsg(val string) {
	p.Msg = val
}
func (p *MockReq) SetStrMap(val map[string]string) {
	p.StrMap = val
}
func (p *MockReq) SetStrList(val []string) {
	p.StrList = val
}

func (p *MockReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MockReq(%+v)", *p)
}

func (p *MockReq) DeepEqual(ano *MockReq) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Msg) {
		return false
	}
	if !p.Field2DeepEqual(ano.StrMap) {
		return false
	}
	if !p.Field3DeepEqual(ano.StrList) {
		return false
	}
	return true
}

func (p *MockReq) Field1DeepEqual(src string) bool {

	if strings.Compare(p.Msg, src) != 0 {
		return false
	}
	return true
}
func (p *MockReq) Field2DeepEqual(src map[string]string) bool {

	if len(p.StrMap) != len(src) {
		return false
	}
	for k, v := range p.StrMap {
		_src := src[k]
		if strings.Compare(v, _src) != 0 {
			return false
		}
	}
	return true
}
func (p *MockReq) Field3DeepEqual(src []string) bool {

	if len(p.StrList) != len(src) {
		return false
	}
	for i, v := range p.StrList {
		_src := src[i]
		if strings.Compare(v, _src) != 0 {
			return false
		}
	}
	return true
}

var fieldIDToName_MockReq = map[int16]string{
	1: "Msg",
	2: "strMap",
	3: "strList",
}

type Exception struct {
	Code int32  `thrift:"code,1" frugal:"1,default,i32" json:"code"`
	Msg  string `thrift:"msg,255" frugal:"255,default,string" json:"msg"`
}

func NewException() *Exception {
	return &Exception{}
}

func (p *Exception) InitDefault() {
}

func (p *Exception) GetCode() (v int32) {
	return p.Code
}

func (p *Exception) GetMsg() (v string) {
	return p.Msg
}
func (p *Exception) SetCode(val int32) {
	p.Code = val
}
func (p *Exception) SetMsg(val string) {
	p.Msg = val
}

func (p *Exception) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Exception(%+v)", *p)
}
func (p *Exception) Error() string {
	return p.String()
}

func (p *Exception) DeepEqual(ano *Exception) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Code) {
		return false
	}
	if !p.Field255DeepEqual(ano.Msg) {
		return false
	}
	return true
}

func (p *Exception) Field1DeepEqual(src int32) bool {

	if p.Code != src {
		return false
	}
	return true
}
func (p *Exception) Field255DeepEqual(src string) bool {

	if strings.Compare(p.Msg, src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_Exception = map[int16]string{
	1:   "code",
	255: "msg",
}

type Mock interface {
	Test(ctx context.Context, req *MockReq) (r string, err error)

	ExceptionTest(ctx context.Context, req *MockReq) (r string, err error)
}

type MockTestArgs struct {
	Req *MockReq `thrift:"req,1" frugal:"1,default,MockReq" json:"req"`
}

func NewMockTestArgs() *MockTestArgs {
	return &MockTestArgs{}
}

func (p *MockTestArgs) InitDefault() {
}

var MockTestArgs_Req_DEFAULT *MockReq

func (p *MockTestArgs) GetReq() (v *MockReq) {
	if !p.IsSetReq() {
		return MockTestArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *MockTestArgs) SetReq(val *MockReq) {
	p.Req = val
}

func (p *MockTestArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *MockTestArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MockTestArgs(%+v)", *p)
}

func (p *MockTestArgs) DeepEqual(ano *MockTestArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Req) {
		return false
	}
	return true
}

func (p *MockTestArgs) Field1DeepEqual(src *MockReq) bool {

	if !p.Req.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_MockTestArgs = map[int16]string{
	1: "req",
}

type MockTestResult struct {
	Success *string `thrift:"success,0,optional" frugal:"0,optional,string" json:"success,omitempty"`
}

func NewMockTestResult() *MockTestResult {
	return &MockTestResult{}
}

func (p *MockTestResult) InitDefault() {
}

var MockTestResult_Success_DEFAULT string

func (p *MockTestResult) GetSuccess() (v string) {
	if !p.IsSetSuccess() {
		return MockTestResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *MockTestResult) SetSuccess(x interface{}) {
	p.Success = x.(*string)
}

func (p *MockTestResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MockTestResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MockTestResult(%+v)", *p)
}

func (p *MockTestResult) DeepEqual(ano *MockTestResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	return true
}

func (p *MockTestResult) Field0DeepEqual(src *string) bool {

	if p.Success == src {
		return true
	} else if p.Success == nil || src == nil {
		return false
	}
	if strings.Compare(*p.Success, *src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_MockTestResult = map[int16]string{
	0: "success",
}

type MockExceptionTestArgs struct {
	Req *MockReq `thrift:"req,1" frugal:"1,default,MockReq" json:"req"`
}

func NewMockExceptionTestArgs() *MockExceptionTestArgs {
	return &MockExceptionTestArgs{}
}

func (p *MockExceptionTestArgs) InitDefault() {
}

var MockExceptionTestArgs_Req_DEFAULT *MockReq

func (p *MockExceptionTestArgs) GetReq() (v *MockReq) {
	if !p.IsSetReq() {
		return MockExceptionTestArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *MockExceptionTestArgs) SetReq(val *MockReq) {
	p.Req = val
}

func (p *MockExceptionTestArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *MockExceptionTestArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MockExceptionTestArgs(%+v)", *p)
}

func (p *MockExceptionTestArgs) DeepEqual(ano *MockExceptionTestArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Req) {
		return false
	}
	return true
}

func (p *MockExceptionTestArgs) Field1DeepEqual(src *MockReq) bool {

	if !p.Req.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_MockExceptionTestArgs = map[int16]string{
	1: "req",
}

type MockExceptionTestResult struct {
	Success *string    `thrift:"success,0,optional" frugal:"0,optional,string" json:"success,omitempty"`
	Err     *Exception `thrift:"err,1,optional" frugal:"1,optional,Exception" json:"err,omitempty"`
}

func NewMockExceptionTestResult() *MockExceptionTestResult {
	return &MockExceptionTestResult{}
}

func (p *MockExceptionTestResult) InitDefault() {
}

var MockExceptionTestResult_Success_DEFAULT string

func (p *MockExceptionTestResult) GetSuccess() (v string) {
	if !p.IsSetSuccess() {
		return MockExceptionTestResult_Success_DEFAULT
	}
	return *p.Success
}

var MockExceptionTestResult_Err_DEFAULT *Exception

func (p *MockExceptionTestResult) GetErr() (v *Exception) {
	if !p.IsSetErr() {
		return MockExceptionTestResult_Err_DEFAULT
	}
	return p.Err
}
func (p *MockExceptionTestResult) SetSuccess(x interface{}) {
	p.Success = x.(*string)
}
func (p *MockExceptionTestResult) SetErr(val *Exception) {
	p.Err = val
}

func (p *MockExceptionTestResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MockExceptionTestResult) IsSetErr() bool {
	return p.Err != nil
}

func (p *MockExceptionTestResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MockExceptionTestResult(%+v)", *p)
}

func (p *MockExceptionTestResult) DeepEqual(ano *MockExceptionTestResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	if !p.Field1DeepEqual(ano.Err) {
		return false
	}
	return true
}

func (p *MockExceptionTestResult) Field0DeepEqual(src *string) bool {

	if p.Success == src {
		return true
	} else if p.Success == nil || src == nil {
		return false
	}
	if strings.Compare(*p.Success, *src) != 0 {
		return false
	}
	return true
}
func (p *MockExceptionTestResult) Field1DeepEqual(src *Exception) bool {

	if !p.Err.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_MockExceptionTestResult = map[int16]string{
	0: "success",
	1: "err",
}

// exceptions of methods in Mock.
var (
	_ error = (*Exception)(nil)
)
